seo:
  site_name: Lichtquelle
  title: Lichtquelle
  description: Ich begleite Menschen mit bewusster energetischer Heilarbeit auf ihrem Weg, ihr Potenzial zu entfalten und zu sich selbst zu finden. Mein Herz schlägt besonders für die Arbeit mit dem Herzenslichtkörper Prozess nach Natara®. In meiner Lichtquelle Sessions begleite ich Dich klar, professionell und intuitiv. Ich helfe Dir bei deinen Anliegen einfühlsam und klärend. Ich möchte Menschen begleiten die sich entschieden haben für sich selbst, für ihre Freiheit, ihre Gesundheit, Kraft, Klarheit und die Bereitschaft ihren eigenen Weg zu gehen.
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url:
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#2e2e2e'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#6B78A5'
  medium_color: '#C8AA64'
  light_color: '#fff7e3'
  v-light_color: '#9CA6CB'
  featured_color: '#d2e6c4'
  accent_color: '#a74a4a'
